### ISSUE TITLE
LSP multi sampler: midi numbers not correct

### ISSUE THREAD

**Issue by grammoboy2** [sadko4u/lsp-plugins#160] opened 2020-12-14 13:49 UTC
C5 is C6 in LSP. So when you set C5, you've to use C6 in your sequencer

**Comment by grammoboy2** [comment] 2020-12-14 13:53
For A3 I need A5 in my sequencer. I think something is wrong here.

**Comment by sadko4u** [comment] 2020-12-14 14:01
The problem is that there is no strict mapping of MIDI octaves to actual octaves.
Some sources define them to start with '-2' (as LSP does in 1.1.26).
Some sources define them to start with '-1' (as LSP will do in new release).
Other sources define them to start with '0'.

So your C5 -> C6 problem will be fixed in the upcoming release.

A3 -> A5 - there's something wrong...

**Comment by grammoboy2** [comment] 2020-12-14 15:11
"A3 -> A5 - there's something wrong..."

I'll keep an eye on it. Let's assume it didn't happen for now.

**Comment by sadko4u** [comment] 2020-12-14 22:44
I've found the change that fixes the problem in git: 6b5cdaf8198c4db48e28270fea49dde5d42c58d7
It is already merged in **devel**.
So I'll close the issue after the 1.1.28 release.

**Comment by sadko4u** [comment] 2020-12-20 23:08
Available in 1.1.28 release!

**Closed by sadko4u** 2020-12-20 23:08 UTC
Labels: PENDING FOR RELEASE, bug

**Comment by grammoboy2** [comment] 2020-12-20 23:12
Gracias!
