### ISSUE TITLE
[Impulse Responses] JACK disconnecting

### ISSUE THREAD

**Issue by CBiX** [sadko4u/lsp-plugins#78] opened 2020-02-18 15:26 UTC
After a while of using the impulse_responses_stereo plugin (as of cd35536 on the hotfix branch), Ardour would lose connection to JACK. I could reproduce the issue inside the profiling runtime and also the stable version from the Arch community repo. Of course, this could be an upstream issue of JACK, but it only ever occured with this plugin so far.

Stacktrace from the profiler:

    Thread 1 "lsp-plugins-pro" received signal SIGPIPE, Broken pipe.
    0x00007ffff7f0868f in write () from /usr/lib/libpthread.so.0
    (gdb) thread apply all bt
    
    Thread 3 (Thread 0x7ffff5990700 (LWP 222344)):
    #0  0x00007ffff7f04cf5 in pthread_cond_wait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
    #1  0x00007ffff7c75060 in ?? () from /usr/lib/libjack.so.0
    #2  0x00007ffff7efe46f in start_thread () from /usr/lib/libpthread.so.0
    #3  0x00007ffff78583d3 in clone () from /usr/lib/libc.so.6
    
    Thread 2 (Thread 0x7ffff645a700 (LWP 222343)):
    #0  0x00007ffff78202d1 in clock_nanosleep@GLIBC_2.2.5 () from /usr/lib/libc.so.6
    #1  0x00007ffff7825bf7 in nanosleep () from /usr/lib/libc.so.6
    #2  0x0000000000478244 in lsp::ipc::Thread::sleep (millis=100) at ipc/Thread.cpp:288
    #3  0x000000000047638c in lsp::ipc::NativeExecutor::run (this=0x7cd880) at ipc/NativeExecutor.cpp:106
    #4  0x000000000047641c in lsp::ipc::NativeExecutor::execute (params=0x7cd880) at ipc/NativeExecutor.cpp:130
    #5  0x0000000000477e9e in lsp::ipc::Thread::run (this=0x7cd888) at ipc/Thread.cpp:85
    #6  0x0000000000477f97 in lsp::ipc::Thread::thread_launcher (arg=0x7cd888) at ipc/Thread.cpp:214
    #7  0x00007ffff7efe46f in start_thread () from /usr/lib/libpthread.so.0
    #8  0x00007ffff78583d3 in clone () from /usr/lib/libc.so.6
    
    Thread 1 (Thread 0x7ffff6add8c0 (LWP 222339)):
    #0  0x00007ffff7f0868f in write () from /usr/lib/libpthread.so.0
    #1  0x00007ffff7c70a0c in ?? () from /usr/lib/libjack.so.0
    #2  0x00007ffff7c770c9 in jack_port_unregister () from /usr/lib/libjack.so.0
    #3  0x000000000040758c in lsp::JACKDataPort::disconnect (this=0x7c0450) at /home/florian/Code/lsp-plugins/include/container/jack/ports.h:121
    #4  0x000000000040a83f in lsp::JACKWrapper::disconnect (this=0x7fffffffdee0) at /home/florian/Code/lsp-plugins/include/container/jack/wrapper.h:628
    #5  0x000000000040b562 in lsp::jack_ui_sync (time=1582039056309, arg=0x7fffffffde60) at jack.cpp:93
    #6  0x000000000058b09a in lsp::tk::LSPTimer::execute_task (this=0x7fffffffde90, time=1582039056309, arg=0x7fffffffde90) at sys/LSPTimer.cpp:81
    #7  0x000000000058afd1 in lsp::tk::LSPTimer::execute (time=1582039056309, arg=0x7fffffffde90) at sys/LSPTimer.cpp:60
    #8  0x0000000000573dc0 in lsp::ws::x11::X11Display::do_main_iteration (this=0x807f30, ts=1582039056309) at X11Display.cpp:435
    #9  0x0000000000573b54 in lsp::ws::x11::X11Display::main (this=0x807f30) at X11Display.cpp:372
    #10 0x0000000000586b72 in lsp::tk::LSPDisplay::main (this=0x7bffe8) at sys/LSPDisplay.cpp:175
    #11 0x000000000040689c in lsp::plugin_ui::main (this=0x7bffa0) at /home/florian/Code/lsp-plugins/include/ui/plugin_ui.h:279
    #12 0x000000000040b8db in lsp::jack_plugin_main (plugin=0x7bfe90, pui=0x7bffa0, argc=1, argv=0x7bed20) at jack.cpp:200
    #13 0x000000000040e992 in lsp_jack_main (plugin_id=0x7fffffffe713 "impulse_responses_stereo", argc=1, argv=0x7bed20) at jack.cpp:267
    #14 0x0000000000411144 in main (argc=2, argv=0x7fffffffe358) at profile.cpp:89

**Comment by sadko4u** [comment] 2020-02-18 20:22
Have you seen this issue in JACK community?
https://github.com/jackaudio/jack2/issues/307

It seems that some versions of jackd do just spontaneously lose connection with clients.
Maybe it's your case.

**Comment by sadko4u** [comment] 2020-02-18 20:22
@falkTX, any comments/ideas?

**Comment by falkTX** [comment] 2020-02-18 21:37
seems like jack client shutdown has been triggered, and the application is not handling it well, leading to a crash.

**Comment by sadko4u** [comment] 2020-02-18 23:24
@falkTX according to the context of the report, the shutdown was an unexpected behaviour. The socket just has been closed and SIGPIPE triggered on socket write.

**Comment by sadko4u** [comment] 2020-02-19 12:32
Created **github-issue-78** branch and committed change that ignores SIGPIPE signal: 5f2f2a566ae26747f711c87c49f7bc24166d99d3
Please try to reproduce the problem again
Also, please explain more details about configuration of JACK server and plugin you're using.

**Comment by CBiX** [comment] 2020-02-19 15:00
I just switched to jack2 (completely forgot jack and jack2 were two different implementations) and everything works without any problems. With legacy JACK I would even start getting crashes when using other plugins, so this clearly looks like an upstream issue of JACK to me.
Still, thanks for your efforts, I love working with your IR plugins!!

**Comment by sadko4u** [comment] 2020-02-19 16:12
Nice to see that problems have been solved.
Anyway, you've a bit hurried closing this topic since it provides some changes in git repository.
I'll close it after the 1.1.14 release.

**Comment by sadko4u** [comment] 2020-02-19 16:16
Merged changes into **devel** branch: 06f82543d014da53bfb987a594b452c6fe8fee66

**Comment by sadko4u** [comment] 2020-02-19 16:16
Removed **github-issue-78** branch.

**Comment by sadko4u** [comment] 2020-03-20 23:37
Changes available in 1.1.14 release!

**Closed by sadko4u** 2020-03-20 23:37 UTC
Labels: PENDING FOR RELEASE, feature request
