### ISSUE TITLE
Parametric EQ midside scaling issue and typo

### ISSUE THREAD

**Issue by ents-hqx** [sadko4u/lsp-plugins#96] opened 2020-04-06 07:34 UTC
Parametric EQ midside has scaling issue when You change frequency, it jiggles right and left like crazy.
Also there is a typo.It is written "Filters Right 0-7" but it should be "Filters Middle 0-7"

**Comment by sadko4u** [comment] 2020-04-06 08:59
What DAW?
Could you please record a video or do a screenshot while reproducing the problem?

**Comment by sadko4u** [comment] 2020-04-06 09:07
I've fixed equalizer labels within #95 issue: 50457df4f4c44fe2c4d29f8a265f32a904fff26b

**Comment by ents-hqx** [comment] 2020-04-06 09:31
Hello

I'm using ardour with lv2 plugin

![scaling](https://user-images.githubusercontent.com/35730375/78544235-82538200-7802-11ea-9a4f-c21002725841.gif)

**Comment by sadko4u** [comment] 2020-04-06 09:58
What version of Ardour?

**Comment by sadko4u** [comment] 2020-04-06 10:03
It seems that Ardour tires to force plugin to set the window size fitting the parent size but plugin resizes back and asks Ardour to minimize the parent window which is actually not done by Ardour.

**Comment by sadko4u** [comment] 2020-04-06 10:03
@x42, any thoughts?

**Comment by ents-hqx** [comment] 2020-04-06 10:38
> What version of Ardour?

5.12.0

**Comment by sadko4u** [comment] 2020-04-06 10:40
I don't see any window border. Is the window maximized or just captured so I don't see the border?

**Comment by ents-hqx** [comment] 2020-04-06 10:54
It captured it that way that it does not show border. I tried PEQ M/S plugin in carla and below 2 pictures right after I opened conf window and then when I changed frequency. Maybe opening first time is wrong size?

![Screenshot from 2020-04-06 13-46-23](https://user-images.githubusercontent.com/35730375/78551242-0c551800-780e-11ea-8572-a99402ce250b.png)

![Screenshot from 2020-04-06 13-46-31](https://user-images.githubusercontent.com/35730375/78551257-11b26280-780e-11ea-82b3-bc1b9d26317a.png)

**Comment by sadko4u** [comment] 2020-04-06 11:09
> Maybe opening first time is wrong size?

Or Ardour is not properly handling (ui:resize)[https://lv2plug.in/ns/extensions/ui/ui.html#resize] request due to some reasons (for me, I can not reproduce the case, all is just fine).

I need additional information:
* What's your OS?
* What hardware architecture do you use?
* What desktop environment do you use?
* Do you use Wayland compositor?
* What are your screen settings and resolution?
* Is your plugin window maximized or just usual non-maximized window?

**Comment by ents-hqx** [comment] 2020-04-06 11:41
I think we are both correct. Ardour does not properly handle resize and initial windows size "seems wrong"

To make my point, here is screenshot of same plugin but M/S and Stereo versions side by side. Initial size after opening. When i change freq, then M/S version resizes to the same size as Stereo version.
![Screenshot from 2020-04-06 14-29-42](https://user-images.githubusercontent.com/35730375/78554500-ee8ab180-7813-11ea-9bf2-657e5dcce0cc.png)

And after I have modified freq. I get this
![Screenshot from 2020-04-06 14-37-22](https://user-images.githubusercontent.com/35730375/78554656-3578a700-7814-11ea-818a-0b351d56862b.png)

As I understand You get right away the second picture?

Below are info You requested

1) Ubuntu 20.04 beta....

2) x86_64

3) Gnome Shell

4) Type=x11

5) 1920x1080

6) Non-maximized

**Comment by sadko4u** [comment] 2020-04-06 11:57
Currently plugin tries to minimize it's size as possible to fit all controls.
There are several requests to make plugin window sizeable as here - #73 
I believe I need to make all plugin windows sizeable but not all widgets are compatible with it now.
I think I'll do it in context of this issue.

Does the problem happen if you manually try to minimize size of plugin in Ardour's window? Does Ardour allow to resize the entire parent window with plugin?

**Comment by ents-hqx** [comment] 2020-04-06 12:36
Cant resize plugin window in ardour or carla

**Comment by x42** [comment] 2020-04-09 02:00
On 4/6/20 1:10 PM, Vladimir Sadovnikov wrote:
>> Maybe opening first time is wrong size?
> 
> Or Ardour is not properly handling (ui:resize)[https://lv2plug.in/ns/extensions/ui/ui.html#resize] request due to some reasons (for me, I can not reproduce the case, all is just fine).

libsuil provides and handles it. Ardour plays no part in this.

**Comment by sadko4u** [comment] 2020-04-09 08:31
@ents-hqx 
Do you use official Ardour build or installed from some repository?

**Comment by ents-hqx** [comment] 2020-04-09 18:00
Ubuntu repo, package name ardour_5.12.0-3ubuntu2

**Comment by sadko4u** [comment] 2020-04-10 00:15
> Ubuntu repo, package name ardour_5.12.0-3ubuntu2

It may be an issue of libsuil which may be used for building ardour. Anyway, need to create virtual machine to perform a check.

**Comment by x42** [comment] 2020-04-10 00:41
On 4/10/20 2:15 AM, Vladimir Sadovnikov wrote:
>> Ubuntu repo, package name ardour_5.12.0-3ubuntu2
> 
> It may be an issue of libsuil which may be used for building ardour. Anyway, need to create virtual machine to perform a check.
> 

If so, use an [ardour-nightly](https://nightly.ardour.org), that uses
recent suil 0.10.6-5-g7c3e3d6 (latest git currently)

**Comment by sadko4u** [comment] 2020-04-12 16:13
@ents-hqx I've committed several changes to the **github-issue-96** branch so now LV2 UI and JACK UI are sizing. You need to confirm that all is OK on your system.

@v-fox It can also be interesting for you.

I couldn't make VST2 UI sizeable currently because I have no idea how to handle minimization of the UI currently. I've handled maximization by catching X11 resize event of the parent window but couldn't handle size decreasing since Ardour's wrapping window does not allow size decreasing after the child's window's size has been increased.
Maybe @x42  can say anything about VST UI sizing support.

**Comment by ents-hqx** [comment] 2020-04-12 17:23
Hey

First of all thank Your for Your hard work. Below is screenshot after I open peq m/s window

![peq_window](https://user-images.githubusercontent.com/35730375/79075254-61a39480-7cfa-11ea-9d20-12246318f720.png)
So it does not fill all window

And then after I resize window it magically fills window
![peq_window_after_resize](https://user-images.githubusercontent.com/35730375/79075301-aa5b4d80-7cfa-11ea-8840-ecb86af2140a.png)

**Comment by sadko4u** [comment] 2020-04-12 21:37
Reproduced on Ubuntu 20.04 in virtual environment:
![image](https://user-images.githubusercontent.com/12834464/79080506-27e48500-7d1e-11ea-9bd5-2a31421aeff6.png)

The problem is, and, @ents-hqx you have not said that, the reason is that I can not make the Ardour's window narrower than it is on the screenshot. Also I observe that Ardour can not make it narrower. For VST is works as expected:
![image](https://user-images.githubusercontent.com/12834464/79080570-b6f19d00-7d1e-11ea-8402-40e2cedd3c75.png)

Since installed ardour5 uses system **suil** library, the problem can be there.
@x42 @drobilla - any thoughts?

**Comment by sadko4u** [comment] 2020-04-12 22:04
The same is true for official Ardour 5.12 build but instead of scaling the window gets centered:
![image](https://user-images.githubusercontent.com/12834464/79081063-a6432600-7d22-11ea-902f-fbdf09e9c0bb.png)
I believe that's not LSP issue anymore.

**Comment by x42** [comment] 2020-04-12 22:05
fixed size GUIs are centered by suil

**Comment by x42** [comment] 2020-04-12 22:07
IIUC the underlying issue is that the size-requirement changes when you modify a control.
The text (here frequency) needs more space "999" -> "1000" which triggers a re-layout and size-request.

**Comment by sadko4u** [comment] 2020-04-12 22:12
I suppose it's a problem of window manager. I can't even resize window for standalone version of plugin:
![image](https://user-images.githubusercontent.com/12834464/79081191-c0313880-7d23-11ea-8cd4-3e0d77c646a1.png)

**Comment by sadko4u** [comment] 2020-04-13 01:03
@ents-hqx 
Please checkout latest changes and test again. Seems that the problem has been fixed.
It seems that newest GTK takes into account size constraints of the nested window. And these size constraints have been set not properly at startup.

**Comment by ents-hqx** [comment] 2020-04-13 06:52
Yees, everything seems to be working as it should. Nice job!

**Comment by sadko4u** [comment] 2020-04-13 08:56
Merged changes into **devel** branch: c733468cb4073b127e4a5ce9e6496d26a640d38f

**Comment by sadko4u** [comment] 2020-04-18 21:36
Available in 1.1.19 release!

**Closed by sadko4u** 2020-04-18 21:36 UTC
Labels: PENDING FOR RELEASE, bug
