### ISSUE TITLE
Attempt at copy/past in standalone plugins blocks mouse & keyboard input in entire user session

### ISSUE THREAD

**Issue by v-fox** [sadko4u/lsp-plugins#77] opened 2020-02-14 20:33 UTC
While I was fiddling with lsp-plugins-mb-compressor-stereo configuration, I had to copy same values for all 8 bands but I was unable to do it in the interface because, when right-click menu with copy & paste options would become visible, suddenly any input in the whole KDE/plasma5 X11 user session would lock-up until compressor is killed from VT-terminal or remotely: mouse buttons and key presses are simply ignored everywhere. Using Ctrl+C/V shortcuts on keyboard does not work either but it's not as bad as locking up user session. It's like LSP GUI interface "captures" focus and is unable to return it, similarly to what often happens in Windows with crashed full-screen applications.

**Comment by sadko4u** [comment] 2020-02-14 20:37
Please explain more detailed how you tried to copy/paste values. With popup parameter window which is called by double-click?

**Comment by sadko4u** [comment] 2020-02-14 20:41
Seems that I've reproduced the problem. An X11 grab is taken by the popup parameter window. Then, when you call a popup-menu, X11 grab is taken by the popup menu. And after you've selected an item in popup menu, the grab gets never returned.

**Comment by sadko4u** [comment] 2020-02-14 22:50
Created branch **github-issue-77**.
Seems to be fixed with this patch: 792cb48db7f0e76a288a3f0c3e961199fd208df4

**Comment by sadko4u** [comment] 2020-02-14 22:50
Please try

**Comment by v-fox** [comment] 2020-02-15 06:31
> Please try

Yep, seems fine now, keyboard shortcuts also working, thanks !

**Comment by sadko4u** [comment] 2020-02-15 09:37
Merged changes into **devel** branch: 34480fc05202cd54751fa722816bd2c4da01b167

**Comment by sadko4u** [comment] 2020-02-15 09:37
Removed **github-issue-77** branch.

**Comment by sadko4u** [comment] 2020-03-20 23:36
Changes available in 1.1.14 release!

**Closed by sadko4u** 2020-03-20 23:36 UTC
Labels: PENDING FOR RELEASE, bug
