### ISSUE TITLE
LV2-Multi Sampler stops working after renaming a session to Ardour 6

### ISSUE THREAD

**Issue by inFlowia** [sadko4u/lsp-plugins#120] opened 2020-06-18 09:52 UTC
But it starts working again if you select the preset again.

It can be quite dangerous for those who do not always save their sampler settings to presets.

**Comment by sadko4u** [comment] 2020-06-18 09:55
From your description it's not clear the user case.
Please provide the shortest list of steps to reproduce.

**Comment by inFlowia** [comment] 2020-06-18 10:00
It was repeated 2 times. 1 time in a large working project and once in a small test project.
Steps:
Create a project, add a MIDI track, add a Multi Sampler 12 stero, configure the sampler pins (add 2 audio ports and connect them to the plug-in), select any preset with the assigned samples, make sure that the sound goes when you click on the piano roll, save and close project, open a project, rename through Session - rename a project, save the project, close the project, open again. Sound will no longer come from the sampler. If you open the sampler, red error messages will appear in the windows of the samples.

**Comment by sadko4u** [comment] 2020-06-18 10:04
Thank you for detailed information, I'll try to reproduce it.

**Comment by inFlowia** [comment] 2020-06-18 10:09
Thank you for cool software)

**Comment by sadko4u** [comment] 2020-06-25 13:56
Not a problem of LSP Plugins.
Just after renaming the session, we get the plugin state:
```
        state:state [
                <http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_0> <AgogoHigh-0.wav> ;
```

While symlink AgogoHigh-0.wav points to invalid file:
```
ls -l plugins/264/state2
итого 104
lrwxrwxrwx 1 sadko users     36 июн 25 16:52 AgogoHigh-0.wav -> ../../../externals/AgogoHigh-0.wav.2
-rw-r--r-- 1 sadko users    493 июн 25 16:52 manifest.ttl
-rw-r--r-- 1 sadko users 100219 июн 25 16:52 state.ttl

ls -l externals/
итого 8
lrwxrwxrwx 1 sadko users 73 июн 25 16:51 AgogoHigh-0.wav -> /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/AgogoHigh-0.wav
lrwxrwxrwx 1 sadko users 74 июн 25 16:52 AgogoHigh-0.wav.2 -> /home/work/Ardour/2020/0625-test-rename/plugins/264/state1/AgogoHigh-0.wav
```

This is probably also a problem of **lilv** library.

**Comment by sadko4u** [comment] 2020-06-25 13:56
@drobilla, @x42, please look.

**Comment by sadko4u** [comment] 2020-06-25 14:04
@x42, steps to reproduce:
1. Create new session, create bus, put multisampler_x12.
2. Open the UI, load some file, close UI.
3. Perform Session -> rename.
4: You will already get inconsistent session, without need to close it.

**Comment by x42** [comment] 2020-06-25 14:10
I cannot reproduce this with other plugins. e.g. https://github.com/x42/zconvo.lv2  so this may not be an upstream bug.

**Comment by sadko4u** [comment] 2020-06-25 15:00
The problem is not reproducible without session reload. So the right scenario is:

1. Create new session, create bus, put multisampler_x12.
2. Open the UI, load some file, close UI.
3. Save sesion, close, open again
4. Perform Session -> rename.
5. You will already get inconsistent session, without need to close it.

Here's the full log of multisampler save/restore:
```
save: mapped path: /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/AgogoHigh-0.wav -> AgogoHigh-0.wav
restore: unmapped path: /home/work/Ardour/2020/0625-test-rename/plugins/408/state1/AgogoHigh-0.wav -> /home/work/Ardour/2020/0625-test-rename/plugins/408/state1/AgogoHigh-0.wav
save: mapped path: /home/work/Ardour/2020/0625-test-rename/plugins/408/state1/AgogoHigh-0.wav -> AgogoHigh-0.wav
```

Boom!

**Comment by sadko4u** [comment] 2022-05-04 00:27
I think this issue can be closed at this moment.

**Closed by sadko4u** 2022-05-04 00:27 UTC
Labels: UPSTREAM BUG
