### ISSUE TITLE
LV2-Multi sampler spoils the preset if you click on the "Save current preset" button in Ardor 6

### ISSUE THREAD

**Issue by inFlowia** [sadko4u/lsp-plugins#119] opened 2020-06-15 11:44 UTC
If, nevertheless, you can click on the “Save current preset” button ([more details here](https://github.com/sadko4u/lsp-plugins/issues/118)), then the preset will “break” - in the window with the thumbnail of the sample the message “unknown error” will be redder and you will have to select the samples again.

Ardour 6
Ubuntu Studio 19.10 64-bit
Multi Sampler x12 Stereo

**Comment by sadko4u** [comment] 2020-06-15 11:54
I believe solving #118 will solve this problem automatically.

**Comment by sadko4u** [comment] 2020-06-15 11:54
Anyway, I'll close this issue when we'll get sure that #118 fixes it.

**Comment by sadko4u** [comment] 2020-06-24 20:19
I've reproduced the problem. It seems to be not a problem of LSP but the problem of improper work of LV2State:mapPath extension when saving/restoring preset in Ardour.

Here's the first save of preset from LSP perspective:
```
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 652] save: save port id=sf_0_0, urid=654 (http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_0), value=/home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit
/AgogoHigh-0.wav
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 664] save: mapped path: /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/AgogoHigh-0.wav -> AgogoHigh-0.wav
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 652] save: save port id=sf_0_1, urid=671 (http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_1), value=/home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit
/China-2.wav
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 664] save: mapped path: /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/China-2.wav -> China-2.wav
```

We see that file /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit
/AgogoHigh-0.wav has been mapped to abstract path AgogoHigh-0.wav
and /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit
/China-2.wav has been mapped to abstract path China-2.wav

Now, let's look at the preset folder:
```
ls -l /home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2
итого 132
lrwxrwxrwx 1 sadko users     73 июн 24 22:43 AgogoHigh-0.wav -> /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/AgogoHigh-0.wav
lrwxrwxrwx 1 sadko users     69 июн 24 22:43 China-2.wav -> /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/China-2.wav
lrwxrwxrwx 1 sadko users     77 июн 24 22:43 HiHatSemiopen-2.wav -> /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/HiHatSemiopen-2.wav
-rw-r--r-- 1 sadko users    491 июн 24 22:43 manifest.ttl
lrwxrwxrwx 1 sadko users     72 июн 24 22:43 RideBell-3.wav -> /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/RideBell-3.wav
lrwxrwxrwx 1 sadko users     72 июн 24 22:43 SnareRim-0.wav -> /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/SnareRim-0.wav
-rw-r--r-- 1 sadko users 103468 июн 24 22:43 test.ttl
lrwxrwxrwx 1 sadko users     71 июн 24 22:43 TomHigh-4.wav -> /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/TomHigh-4.wav
```

We see that for each file there is a corresponding symbolic link created.
Inside the **state.ttl** file we see the following data:
```
        state:state [
                <http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_0> <AgogoHigh-0.wav> ;
                <http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_1> <China-2.wav> ;
```

So the preset has been correctly saved.

Now, we will make some UI manipulations to mark the preset as dirty and save it again.
As usual, plugin maps the path using LV2State:mapPath:
```
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 652] save: save port id=sf_0_0, urid=654 (http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_0), value=/home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/Ag
ogoHigh-0.wav
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 652] save: save port id=sf_0_1, urid=671 (http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_1), value=/home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/Ch
ina-2.wav
```

Now let's look into preset:
```
        state:state [
                <http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_0> <AgogoHigh-0.wav> ;
                <http://lsp-plug.in/plugins/lv2/multisampler_x12/ports#sf_0_1> <China-2.wav> 
```

Nothing special, all is as expected.
But what's with the preset directory?
```
ls -l /home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2
итого 108
-rw-r--r-- 1 sadko users    491 июн 24 23:10 manifest.ttl
-rw-r--r-- 1 sadko users 103468 июн 24 23:10 test.ttl
```

Whoops, symbolic links are missing.

Moreover, after call of LV2State:save (which saves the patch) it immediately calls LV2State:restore (which applies patch settings to plugin). Now let's see to the restore log:
```
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 722] restore: unmapped path: /home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/AgogoHigh-0.wav -> /home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/AgogoHigh-0.wav
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 631] set_string: submitting path to '/home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/AgogoHigh-0.wav' (length = 70), flags=0x4
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 722] restore: unmapped path: /home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/China-2.wav -> /home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/China-2.wav
[TRC][/home/sadko/eclipse/lsp-plugins/include/container/lv2/ports.h: 631] set_string: submitting path to '/home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/China-2.wav' (length = 66), flags=0x4
```

So the LV2State:mapPath could not convert the abstract path AgogoHigh-0.wav to /home/sadko/.hydrogen/data/drumkits/Forzee Stereo Drumkit/AgogoHigh-0.wav because the symbolic link is missing and unmapped it as being the file  /home/sadko/.lv2/LSP_Multi-Sampler_x12_Stereo_test.lv2/AgogoHigh-0.wav which is wrong.

So It's not a problem of LSP Mutlisampler.
I think @x42, @drobilla and @pauldavisthefirst should clarify the situation

**Comment by sadko4u** [comment] 2020-06-24 21:07
Moreover, I've met that lilv spoils the file name and replaces it with symlink name on the first state load.
Consider there are two files in different folders 'AgogoHigh-0.wav'. The first one will be replaced as 'AgogoHigh-0.wav' but the second with 'AgogoHigh-0.wav.2'.
That's bad practice since some plugins may expect to receive original file name. Ater state load, the user will see some strange 'AgogoHigh-0.wav.2' in the interface which was never used before:
![image](https://user-images.githubusercontent.com/12834464/85627857-de96a700-b677-11ea-8d95-437baeef110f.png)

**Comment by sadko4u** [comment] 2022-05-04 00:27
I think this issue can be closed at this moment.

**Closed by sadko4u** 2022-05-04 00:27 UTC
Labels: UPSTREAM BUG
