### ISSUE TITLE
Reaper is crashing on save

### ISSUE THREAD

**Issue by porzione** [sadko4u/lsp-plugins#243] opened 2022-04-18 12:33 UTC
I found the issue with 1.2.0 (arch linux 1.2.0-2) - Reaper is crashing when I'm trying to save preset state using "save" button in plugin itself. This happens with vst and lv2 versions of sidechain compressor stereo even in default plugin state. 
I don't know whose error this is and wrote on the Reaper.fm forum too.

**Comment by ElizabethHarmon** [comment] 2022-04-18 14:00
Yep, crashes for me too using binaries directly from https://lsp-plug.in/ with REAPER v.6.53

**Comment by sadko4u** [comment] 2022-04-18 14:42
Hello!
This looks like a duplicate of # 231
The fix will be available in 1.2.1 release.
Sorry.

**Comment by porzione** [comment] 2022-04-18 15:08
@sadko4u nothing to be sorry for, thanks for your work!

**Comment by sadko4u** [comment] 2022-05-04 00:23
Available in 1.2.1.

**Closed by sadko4u** 2022-05-04 00:23 UTC
Labels: bug, duplicate, PENDING FOR RELEASE
