### ISSUE TITLE
Support of LSP Plugins withing OBS

### ISSUE THREAD

**Issue by halirutan** [sadko4u/lsp-plugins#256] opened 2022-06-22 00:50 UTC
First off, these plugins are awesome. I love the parametric EQ and it works really nice with, e.g. Carla.

It would be helpful if these plugins could be used within OBS, but I couldn't get them to work with the VST2 host audio filter shipped with OBS and the [LV2 host plugin for OBS](https://github.com/ivyl/obs-lv2) didn't work as well. For VST2, the UI simply shows a black screen. The LV2 host opens the UI windows but shows the actual UI content as a teeny tiny graphic in the upper left corner as seen here:

![OBS_LSP_Parametric_EQ_UI](https://user-images.githubusercontent.com/511683/174917370-c2b91a2e-e67f-4340-8c0f-8026ff2b804d.png)

I know that this is not your problem and definitely not a bug in the LSP plugins. On the other hand, OBS is used by most streamers and having the ability to use the plugins there would probably give a push to the project (not that it needs it).

Question: Has anyone ever looked into that and has a solution? The LV2 plugin linked above is not too big and I looked into the implementation, but I wasn't able to fix the UI size. Would you consider working on OBS support?

**Comment by sadko4u** [comment] 2022-06-22 20:14
That looks like the UI is VERY, VERY small.
That's strange. Maybe something related to the scaling factor of the display - `lv2:scaleFactor`:
http://lv2plug.in/ns/extensions/ui#scaleFactor

Need to check it.

**Comment by halirutan** [comment] 2022-06-22 23:52
@sadko4u Here, I'm on Ubuntu 20.04 and using OBS 27.2.4, the latest available version. However, the reason why you couldn't load the LV2 version is because you need the LV2 plugin host for OBS first: https://github.com/ivyl/obs-lv2

Compiling and copying this worked without hiccups on my machine. I used the "Single User install" as described in the README which consists of just copying the `.so` into the appropriate plugins folder. After that and restarting OBS, you'll have an "LV2 filter" that you can add just like the VST2 filter.

**Comment by karunsiri** [comment] 2022-08-26 13:12
I can confirm the black screen issue with VST plugins.
![Screenshot from 2022-08-26 20-02-34](https://user-images.githubusercontent.com/1308495/186909585-e24008a3-2a5c-4b3e-95f5-50417ea41a2e.png)

OS: Fedora 36
OBS: 27.2.4 (Flatpak version)
Installed libraries:
- glibc
- cairo and libcairo
- libsndfiles 
- freetype and libfreetype
- libGL (for Fedora it's mesa-libGL)

The OBS Log doesn't show anything when opening a plugin UI. I have no idea where to start debugging this but I'm more than glad to provide anything to help debug this.

**Comment by sadko4u** [comment] 2022-08-26 14:25
The problem is reproducible on my machine. I'll check what's happening.

**Comment by sadko4u** [comment] 2022-08-26 14:53
I have built LSP Plugins with trace log enabled and looking into the logs.
Now, what I see:
- The UI is properly created by the VST2 `effEditOpen` call.
- The UI is properly closed by the VST2 `effEditClose` call.

But I don't observe any VST2 `effEditIdle` by the host. This is important thing because according to the VST 2.x specification:
```
    effEditIdle is called by the host for the custom UI editor to process events from windowing subsystem
```

The main event loop of plugin is based on processing the `effEditIdle` event.

**Comment by sadko4u** [comment] 2022-08-26 14:58
This is improper behaviour of the host plugin.
As a workaround, I can try to provide the workaround for this case. But, anyway, it is a good reason to report the bug to OBS community.

**Comment by sadko4u** [comment] 2022-08-26 15:53
Seems that [this workaround](https://github.com/lsp-plugins/lsp-plugin-fw/commit/92c21e16519bda5748d4d7c4928e47695ee347c1) helped to fix the VST2 problem:
![изображение](https://user-images.githubusercontent.com/12834464/186940729-1cc5c16a-d391-4468-87c9-e275048079b1.png)

Will be available in 1.2.3 release.

**Comment by sadko4u** [comment] 2022-08-26 18:26
@halirutan in my installation of this OBS plugin all LV2 plugins are being ignored:
```
LSP Compressor LeftRight filtered out - class not supported
LSP Compressor Mono filtered out - class not supported
LSP Compressor MidSide filtered out - class not supported
LSP Compressor Stereo filtered out - class not supported
LSP Crossover LeftRight x8 filtered out - class not supported
LSP Crossover Mono x8 filtered out - class not supported
LSP Crossover MidSide x8 filtered out - class not supported
LSP Crossover Stereo x8 filtered out - class not supported
LSP Dynamic Processor LeftRight filtered out - class not supported
LSP Dynamic Processor Mono filtered out - class not supported
LSP Dynamic Processor MidSide filtered out - class not supported
LSP Dynamic Processor Stereo filtered out - class not supported

```

Do you have the same behaviour?

**Comment by sadko4u** [comment] 2022-08-26 18:44
Submitted bugs to upstream of https://github.com/ivyl/obs-lv2/:
* https://github.com/ivyl/obs-lv2/issues/8 - Non-trivial designated initializers not supported
* https://github.com/ivyl/obs-lv2/issues/9 - Bad plugin class filtering

**Comment by sadko4u** [comment] 2022-08-26 18:56
After removing the annoying filtering of plugins by plugin class, the plugin with UI works for me:
![изображение](https://user-images.githubusercontent.com/12834464/186972865-e070e296-eb2f-424a-b931-11cd668111bb.png)

I think, all further OBS bugs related to LV2 should be reported here: https://github.com/ivyl/obs-lv2/issues

**Comment by sadko4u** [comment] 2022-08-26 20:32
Seems that I've found the bug. Just need to understand the reason.

**Comment by karunsiri** [comment] 2022-08-27 05:32
@sadko4u You are legend :100: :1st_place_medal:

**Comment by halirutan** [comment] 2022-08-27 13:59
@sadko4u Can you give some guidance about how to build `lsp-plugins` with your patched `lsp-plugins-fw` version on the devel branch? When I clone `lsp-plugins` and follow the make config/fetch approach everything works fine (I restricted features to `vst2` only atm).

What I tried then is a `make clean`, go into the `modules/lsp-plugins-fw` folder and checkout the `devel` branch manually. However, then I'm present with compiler errors (attached at the end). I assume that I have to build more recent versions for all other modules as well, but I'm not sure how to do that when I look at `module.mk`. Is there a trick?

```
In file included from main/core/Resources.cpp:23:
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/core/Resources.h:86:9: error: ‘LSP_HIDDEN_MODIFIER’ does not name a type
   86 |         LSP_HIDDEN_MODIFIER
      |         ^~~~~~~~~~~~~~~~~~~
  g++  [lsp-common-lib] main/stdio.cpp
main/core/Resources.cpp:131:9: error: ‘LSP_HIDDEN_MODIFIER’ does not name a type
  131 |         LSP_HIDDEN_MODIFIER
      |         ^~~~~~~~~~~~~~~~~~~
main/core/Resources.cpp:87:35: warning: ‘lsp::resource::ILoader* lsp::core::create_directory_loader()’ defined but not used [-Wunused-function]
   87 |         static resource::ILoader *create_directory_loader()
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:698: /home/patrick/tmp/lsp-plugins/.build/host/lsp-plugin-fw/main/core/Resources.o] Error 1
make[3]: *** Waiting for unfinished jobs....
  g++  [lsp-runtime-lib] main/expr/Expression.cpp
  g++  [lsp-runtime-lib] main/expr/format.cpp
make[5]: Entering directory '/home/patrick/tmp/lsp-plugins/modules/lsp-tk-lib/src'
  g++  [lsp-tk-lib] main/helpers/draw.cpp
  ld   [lsp-r3d-iface] lsp-r3d-iface.o
  g++  [lsp-dsp-lib] main/generic/generic.cpp
make[5]: Leaving directory '/home/patrick/tmp/lsp-plugins/modules/lsp-r3d-iface/src'
make[4]: Leaving directory '/home/patrick/tmp/lsp-plugins/modules/lsp-r3d-iface'
  g++  [lsp-dsp-lib] main/x86/x86.cpp
In file included from /home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug.h:35,
                 from /home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/core/KVTDispatcher.h:28,
                 from main/core/KVTDispatcher.cpp:23:
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:51:35: error: variable ‘lsp::plug::LSP_HIDDEN_MODIFIER lsp::plug::Factory’ has initializer but incomplete type
   51 |         class LSP_HIDDEN_MODIFIER Factory
      |                                   ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:52:9: warning: extended initializer lists only available with ‘-std=c++11’ or ‘-std=gnu++11’
   52 |         {
      |         ^
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:53:13: error: expected primary-expression before ‘private’
   53 |             private:
      |             ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:53:13: error: expected ‘}’ before ‘private’
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:52:9: note: to match this ‘{’
   52 |         {
      |         ^
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:53:13: error: expected ‘,’ or ‘;’ before ‘private’
   53 |             private:
      |             ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:56:13: error: expected unqualified-id before ‘private’
   56 |             private:
      |             ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:58:17: error: ‘Factory’ does not name a type
   58 |                 Factory                *pNext;
      |                 ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:63:13: error: expected unqualified-id before ‘public’
   63 |             public:
      |             ^~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:65:26: error: ISO C++ forbids declaration of ‘Factory’ with no type [-fpermissive]
   65 |                 explicit Factory(factory_func_t func, const meta::plugin_t **list, size_t items);
      |                          ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:65:17: error: ‘explicit’ outside class declaration
   65 |                 explicit Factory(factory_func_t func, const meta::plugin_t **list, size_t items);
      |                 ^~~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:66:26: error: ISO C++ forbids declaration of ‘Factory’ with no type [-fpermissive]
   66 |                 explicit Factory(factory_func_t func, const meta::plugin_t **list);
      |                          ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:66:17: error: ‘explicit’ outside class declaration
   66 |                 explicit Factory(factory_func_t func, const meta::plugin_t **list);
      |                 ^~~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:67:25: error: declaration of ‘~ lsp::plug::Factory’ as non-member
   67 |                 virtual ~Factory();
      |                         ^~~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:69:13: error: expected unqualified-id before ‘public’
   69 |             public:
      |             ^~~~~~
  g++  [lsp-dsp-units] main/3d/bsp/context.cpp
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:80:24: error: ‘Factory’ does not name a type
   80 |                 inline Factory                 *next()      { return pNext;             }
      |                        ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:82:13: error: expected unqualified-id before ‘public’
   82 |             public:
      |             ^~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:96:17: error: ‘virtual’ outside class declaration
   96 |                 virtual Module                 *create(const meta::plugin_t *meta) const;
      |                 ^~~~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:96:84: error: non-member function ‘lsp::plug::Module* lsp::plug::create(const plugin_t*)’ cannot have cv-qualifier
   96 |                 virtual Module                 *create(const meta::plugin_t *meta) const;
      |                                                                                    ^~~~~
/home/patrick/tmp/lsp-plugins/modules/lsp-plugin-fw/include/lsp-plug.in/plug-fw/plug/Factory.h:99:1: error: expected declaration before ‘}’ token
   99 | } /* namespace lsp */
      | ^
```

**Comment by sadko4u** [comment] 2022-08-27 19:32
@halirutan that seems that you're trying to mix the `devel` branch with non-devel modules.

To just apply patch to the master branch, you need to do the following thing:
```
git clone https://github.com/sadko4u/lsp-plugins.git
make config
make fetch
<apply patch to modules/lsp-plugin-fw directory>
make
sudo make install
```

**Comment by sadko4u** [comment] 2022-08-27 19:34
To build `devel` branch, you need to do the following:
```
git checkout -b devel origin/devel
make config
make fetch
make
sudo make install
```

There are no usual submodules, so you always need to synchronize submodules with the branch of the project by issuing `make fetch` command. Also the configuration code has changed, so you also need to issue `make config` to rewrite the build configuration file.

**Comment by halirutan** [comment] 2022-08-27 22:51
@sadko4u Perfect. Final question: Is it possible to donate something through the linked Paypal account and be sure you can access the funds?

**Comment by sadko4u** [comment] 2022-08-28 00:11
No, the cryptocurrency is the only way at this moment or Patreon as a piggy bank for the time when I will be available to cash the money out. Paypal has banned any money transfers for russian citizens at this moment.

**Comment by halirutan** [comment] 2022-08-28 14:47
Thanks. Don't be surprised that there are two transactions. I wanted to test it first. And it's not an adequate payment for such awesome work, just a small token of appreciation for your efforts.

**Comment by sadko4u** [comment] 2022-08-28 16:27
Please don't close tickets. I'll do it when the 1.2.3 release will be ready.

**Comment by sadko4u** [comment] 2022-08-28 16:32
@halirutan Received the donations, thank you!

**Closed** 2022-09-07 11:03 UTC
Labels: discuss, PENDING FOR RELEASE, UPSTREAM BUG
