### ISSUE TITLE
Buttons in VST plugins don't always function on first mouse click

### ISSUE THREAD

**Issue by JamesPeters667** [sadko4u/lsp-plugins#112] opened 2020-05-30 21:53 UTC
VST plugins of the latest master branch (which includes changes from issue 109) have this behavior. This behavior probably existed in the previous versions, but I didn't notice it until now.

When clicking on a button, the indicator will "illuminate" as though the function is active, but sometimes the function is not actually active. Clicking again a few times will make the function active. Visual feedback in the display area of the plugin confirms this behavior (and the behavior can be heard).

The behavior is often repeatable by sequentially pressing the button on/off several times. It sometimes requires pressing the buttons many times, but I've been able to repeat the behavior in several plugins within 10 seconds of button pressing.

I've noticed this behavior in the following plugins:

Multiband Compressor (active/on/solo/mute)
Graphic EQ (active/on/solo/mute)
Dynamic Processor (listen)

**Comment by sadko4u** [comment] 2020-05-31 01:06
Will check it ASAP

**Comment by sadko4u** [comment] 2020-06-02 11:21
Can not reproduce the case. Tried to push solo/on buttons within few minutes.
REAPER 6.08

**Comment by sadko4u** [comment] 2020-06-02 11:42
Reaper 6.11. Still not reproducible for me.
Any suggestions how to catch it up?

**Comment by JamesPeters667** [comment] 2020-06-02 16:12
I just tested again on 2 different computers. 

My primary computer:

-updated Xubuntu 20.04 (XFCE)
-REAPER 6.11 with customized configuration
-AMD Ryzen 7 3700X CPU
-LSP VST plugins version 1.1.22

My secondary computer:

-fresh install of Xubuntu 20.04 (XFCE)
-fresh install of REAPER 6.11 (default configuration)
-Intel i3 6300 CPU
-LSP VST plugins version 1.1.22

On the primary computer, it's now more difficult to get this behavior to happen (using LSP version 1.1.22). It seems something may have improved this situation since I noticed this with the 1.1.21 version. But I am still able to make it happen after several clicks. See the geq1/geq2 JPG files attached and notice the difference in the 2.5K band (solo/not solo) and how the displays look. It took pressing the solo button about 15 cycles of on/off for this to happen.

![geq1](https://user-images.githubusercontent.com/64047181/83543225-b88b4600-a4c1-11ea-8c2c-69e3949167fa.jpg)

![geq2](https://user-images.githubusercontent.com/64047181/83543242-be812700-a4c1-11ea-8153-1ce89bc3a779.jpg)

On the secondary computer, it seems I can reproduce this much more quickly.

While testing this with the multiband compressors on the primary computer,  I didn't notice the behavior again, but I noticed something else. See mb1/mb2 JPG files attached. I was pressing the "enable" button on and off for band 4 (unlabeled button on the top row which enables/disables the band). Sometimes band 2 (the nearest active band) would extend its frequency range up to 3984 Hz, and sometimes it would remain at 632 Hz.

![mb1](https://user-images.githubusercontent.com/64047181/83543268-cb9e1600-a4c1-11ea-8c07-7f9a13cd16c6.jpg)

![mb2](https://user-images.githubusercontent.com/64047181/83543276-ce990680-a4c1-11ea-894c-4aab1c217861.jpg)

What Linux distro are you using? Maybe I can install that on the secondary computer to test, since I don't use that computer for much. (I'm not that good with Linux so there's a possibility I'd have problems with a distro requiring more command-line steps to install/maintain).

**Comment by sadko4u** [comment] 2020-06-02 19:26
I'm using openSUSE Leap 15.1. That's strange and looks like changes are just not delivered from UI to the DSP code.

**Comment by sadko4u** [comment] 2020-06-02 19:28
I have Ubuntu 20.4 in virtual environment and can try to reproduce it there...

**Comment by sadko4u** [comment] 2020-06-02 20:11
@JamesPeters667 before you'll do something, please try latest changes in **github-issue-112** branch: 7007ff569a4e94fb48d3b1d4747c72b125a3c3da

**Comment by JamesPeters667** [comment] 2020-06-02 20:59
That appears to have fixed all these issues I have mentioned. I tested it on both computers. Thank you again! (and I was just about to install OpenSuse.) :)

**Comment by sadko4u** [comment] 2020-06-02 21:06
Nice to see that problem has been solved.

**Comment by sadko4u** [comment] 2020-06-02 21:09
Merged changes into **devel** branch: c2df24f751631f7c2d452ad7dbd79780bb4c46dc
Removed **github-issue-112** branch

**Comment by sadko4u** [comment] 2020-07-16 19:03
Available in 1.1.24!

**Closed by sadko4u** 2020-07-16 19:03 UTC
Labels: bug
